'use strict';
import { isDOMElement, PREFIX } from './utils';

let prepareConfig = function prepareConfig(params) {
  let config = {
    input: isDOMElement(params.input) ? params.input : undefined,
    id: params.id !== undefined ? parseInt(params.id, 10) : 0
  };

  //Ensure non-existing ID for autogenerated values
  if (typeof config.id === 'number') {
    let el;
    do {
      config.id += 1;
      el = document.getElementById(`${PREFIX}-${config.id}`);
    } while (el);
    config.id = parseInt(config.id, 10);
  }

  if (!config.input) {
    throw 'Param `input` is mandarory';
  }

  return config;
};

export default prepareConfig;
